[versions]

# the jdk used to build the project
jdk = "11"
# the jdk used in packaging
jvmTarget = "1.8"
kotlin = "1.8.22"
kotlinApi = "1.7"
ktlint-lib = "0.50.0"
ktrules-dev = "1.1.4-SNAPSHOT"
ktrules-released = "1.1.3"

benManes-versions = "0.47.0"
dependencyAnalysis = "1.20.0"
detekt = "1.23.0"
diffplug-spotless = "6.19.0"
dokka = "1.8.20"
dropbox-dependencyGuard = "0.4.3"
ec4j = "0.3.0"
github-release = "2.4.1"
google-ksp = "1.8.22-1.0.11"
jimfs = "1.2"
jUnit = "5.9.3"
jetbrains-changelog = "2.1.0"
jetbrains-markdown = "0.4.1"
johnrengelman-shadow = "8.1.1"
kotest = "5.6.2"
kotlinx-binaryCompatibility = "0.13.2"
prettier-lib = "2.8.4"
prettier-plugin-sh = "0.12.8"
rickBusarow-doks = "0.1.4"
rickBusarow-ktlint = "0.1.8"
rickBusarow-moduleCheck = "0.12.5"
slf4j = "2.0.7"
vanniktech-publish = "0.25.3"

[plugins]

benManes = { id = "com.github.ben-manes.versions", version.ref = "benManes-versions" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
doks = { id = "com.rickbusarow.doks", version.ref = "rickBusarow-doks" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dropbox-dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dropbox-dependencyGuard" }
github-release = { id = "com.github.breadmoirai.github-release", version.ref = "github-release" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
jetbrains-changelog = { id = "org.jetbrains.changelog", version.ref = "jetbrains-changelog" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-binaryCompatibility = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibility" }
ktlint = { id = "com.rickbusarow.ktlint", version.ref = "rickBusarow-ktlint" }
moduleCheck = { id = "com.rickbusarow.module-check", version.ref = "rickBusarow-moduleCheck" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "johnrengelman-shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "diffplug-spotless" }
vanniktech-publish = { id = "com.vanniktech.maven.publish.base", version.ref = "vanniktech-publish" }

[libraries]
benManes-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "benManes-versions" }

dependency-analysis-gradle-plugin = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dependencyAnalysis" }

detekt-api = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
detekt-cli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-rules-libraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
detekt-rules-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detekt" }
detekt-test = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
detekt-test-utils = { module = "io.gitlab.arturbosch.detekt:detekt-test-utils", version.ref = "detekt" }

diffplug-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "diffplug-spotless" }

dokka-all-modules = { module = "org.jetbrains.dokka:all-modules-page-plugin", version.ref = "dokka" }
dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
dokka-versioning = { module = "org.jetbrains.dokka:versioning-plugin", version.ref = "dokka" }

dropbox-dependencyGuard = { module = "com.dropbox.dependency-guard:dependency-guard", version.ref = "dropbox-dependencyGuard" }

ec4j-core = { module = "org.ec4j.core:ec4j-core", version.ref = "ec4j" }

github-release = { module = "com.github.breadmoirai:github-release", version.ref = "github-release" }

google-auto-service-annotations = "com.google.auto.service:auto-service-annotations:1.1.1"
google-auto-service-processor = "com.google.auto.service:auto-service:1.1.1"

google-ksp = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "google-ksp" }

jetbrains-changelog-gradle-plugin = { module = "org.jetbrains.intellij.plugins:gradle-changelog-plugin", version.ref = "jetbrains-changelog" }

jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "jetbrains-markdown" }

jimfs = { module = "com.google.jimfs:jimfs", version.ref = "jimfs" }

johnrengelman-shadowJar = { module = "com.github.johnrengelman:shadow", version.ref = "johnrengelman-shadow" }

junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jUnit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jUnit" }

kotest-assertions-api = { module = "io.kotest:kotest-assertions-api", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-assertions-shared = { module = "io.kotest:kotest-assertions-shared", version.ref = "kotest" }
kotest-common = { module = "io.kotest:kotest-common", version.ref = "kotest" }
kotest-extensions = { module = "io.kotest:kotest-extensions", version.ref = "kotest" }
kotest-property-jvm = { module = "io.kotest:kotest-property-jvm", version.ref = "kotest" }
kotest-runner-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }

kotlin-annotation-processing = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-embeddable", version.ref = "kotlin" }
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-sam-with-receiver = { module = "org.jetbrains.kotlin:kotlin-sam-with-receiver", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

kotlinx-binaryCompatibility = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-binaryCompatibility" }

ktlint47-core = "com.pinterest.ktlint:ktlint-core:0.47.1"
ktlint47-ruleset-experimental = "com.pinterest.ktlint:ktlint-ruleset-experimental:0.47.1"
ktlint47-ruleset-standard = "com.pinterest.ktlint:ktlint-ruleset-standard:0.47.1"
ktlint47-test = "com.pinterest.ktlint:ktlint-test:0.47.1"

ktlint48-core = "com.pinterest.ktlint:ktlint-core:0.48.2"
ktlint48-ruleset-experimental = "com.pinterest.ktlint:ktlint-ruleset-experimental:0.48.2"
ktlint48-ruleset-standard = "com.pinterest.ktlint:ktlint-ruleset-standard:0.48.2"
ktlint48-test = "com.pinterest.ktlint:ktlint-test:0.48.2"

ktlint49-core = "com.pinterest.ktlint:ktlint-core:0.49.1"
ktlint49-cli-ruleset-core = "com.pinterest.ktlint:ktlint-cli-ruleset-core:0.49.1"
ktlint49-rule-engine-core = "com.pinterest.ktlint:ktlint-rule-engine-core:0.49.1"
ktlint49-rule-engine = "com.pinterest.ktlint:ktlint-rule-engine:0.49.1"
ktlint49-ruleset-experimental = "com.pinterest.ktlint:ktlint-ruleset-experimental:0.49.1"
ktlint49-ruleset-standard = "com.pinterest.ktlint:ktlint-ruleset-standard:0.49.1"
ktlint49-test = "com.pinterest.ktlint:ktlint-test:0.49.1"

ktlint-cli-ruleset-core = { module = "com.pinterest.ktlint:ktlint-cli-ruleset-core", version.ref = "ktlint-lib" }
ktlint-rule-engine-core = { module = "com.pinterest.ktlint:ktlint-rule-engine-core", version.ref = "ktlint-lib" }
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint-lib" }
ktlint-ruleset-experimental = { module = "com.pinterest.ktlint:ktlint-ruleset-experimental", version.ref = "ktlint-lib" }
ktlint-ruleset-standard = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlint-lib" }
ktlint-test = { module = "com.pinterest.ktlint:ktlint-test", version.ref = "ktlint-lib" }

rickBusarow-ktlint = { module = "com.rickbusarow.ktlint:ktlint-gradle-plugin", version.ref = "rickBusarow-ktlint" }

rickBusarow-ktrules = { module = "com.rickbusarow.ktrules:ktrules", version.ref = "ktrules-released" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

vanniktech-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "vanniktech-publish" }

zacSweers-auto-service-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.0.0"

[bundles]
jUnit = [
  "junit-engine",
  "junit-jupiter",
  "junit-jupiter-api",
  "junit-params",
]
kotest = [
  "kotest-assertions-api",
  "kotest-assertions-core-jvm",
  "kotest-assertions-shared",
  "kotest-common",
  "kotest-extensions",
  "kotest-property-jvm",
]
